# Generated by Django 4.0.4 on 2022-05-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='Activities',
        ),
    ]
