# Generated by Django 4.0.4 on 2022-09-03 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='housewars.activity'),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='housewars.activity'),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='award',
            field=models.ForeignKey(limit_choices_to=models.Q(('activity__award', django.db.models.expressions.F('activity'))), on_delete=django.db.models.deletion.CASCADE, to='housewars.award'),
        ),
    ]
