# Generated by Django 4.0.4 on 2022-09-03 05:46

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0002_alter_award_activity_alter_pointsentry_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housewars.activity'),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='award',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='activity', chained_model_field='activity__name', null=True, on_delete=django.db.models.deletion.CASCADE, to='housewars.award'),
        ),
    ]
