# Generated by Django 4.0.4 on 2022-05-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0003_alter_activity_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='grade',
            field=models.IntegerField(choices=[(9, '9th/Freshman'), (10, '10th/Sophomore'), (11, '11th/Junior'), (12, '12th/Senior')]),
        ),
    ]
