# Generated by Django 4.0.4 on 2022-09-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0003_alter_activity_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointsentry',
            unique_together=set(),
        ),
    ]
