# Generated by Django 4.0.4 on 2022-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0005_alter_entry_activity2'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='house',
            field=models.CharField(choices=[('HAWK', 'Hawk'), ('GREATGREY', 'Great Grey'), ('EAGLE', 'Eagle'), ('SNOWY', 'Snowy')], default='HAWK', max_length=15),
            preserve_default=False,
        ),
    ]
