# Generated by Django 4.0.4 on 2022-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0006_entry_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activity2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity2', to='housewars.activity'),
        ),
    ]
