# Generated by Django 4.0.4 on 2022-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0007_alter_entry_activity2'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='session1_signups',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='session2_signups',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
