# Generated by Django 4.0.4 on 2022-09-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0005_alter_teacher_grade'),
        ('housewars', '0007_alter_facilitator_activity'),
    ]

    operations = [
    ]
