# Generated by Django 4.0.4 on 2022-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0008_activity_session1_signups_activity_session2_signups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='session1_signups',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='session2_signups',
            field=models.IntegerField(default=0),
        ),
    ]
