# Generated by Django 4.0.4 on 2023-05-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0008_merge_20220907_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='room_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
