# Generated by Django 4.0.4 on 2022-05-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0011_house_alter_activity_managers_alter_entry_house'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='house',
            field=models.CharField(choices=[('HAWK', 'Hawk'), ('GREATGREY', 'Great Grey'), ('EAGLE', 'Eagle'), ('SNOWY', 'Snowy')], max_length=15),
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
