# Generated by Django 4.0.4 on 2022-05-21 18:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0013_house_pointsentry_userentry_delete_entry'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pointsentry',
            managers=[
                ('hawk', django.db.models.manager.Manager()),
            ],
        ),
    ]
