# Generated by Django 4.0.4 on 2022-05-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0014_alter_pointsentry_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pointsentry',
            managers=[
            ],
        ),
    ]
