# Generated by Django 4.0.4 on 2022-05-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0015_alter_pointsentry_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userentry',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='pointsentry',
            old_name='reason',
            new_name='comment',
        ),
    ]
