# Generated by Django 4.0.4 on 2022-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0016_alter_userentry_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
