# Generated by Django 4.0.4 on 2022-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0017_alter_house_points_alter_pointsentry_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsentry',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
