# Generated by Django 4.0.4 on 2022-08-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0018_alter_pointsentry_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsentry',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
