# Generated by Django 4.0.4 on 2022-08-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0020_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='housewars.activity'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='housewars.house'),
        ),
    ]
