# Generated by Django 4.0.4 on 2022-08-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0022_alter_teacher_activity_alter_teacher_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='activity',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='housewars.activity'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='house',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='housewars.house'),
        ),
    ]
