# Generated by Django 4.0.4 on 2022-08-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0023_alter_teacher_activity_alter_teacher_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsentry',
            name='comment',
        ),
        migrations.AddField(
            model_name='pointsentry',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
