# Generated by Django 4.0.4 on 2022-09-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0024_remove_pointsentry_comment_pointsentry_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.IntegerField(blank=True, choices=[(30, '30'), (60, '60')], default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('house', 'grade')},
        ),
    ]
