# Generated by Django 4.0.4 on 2022-09-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewars', '0025_alter_activity_time_alter_teacher_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
